# site settings
title: 鈴木このみコールガイド
subtitle: 鈴木このみの楽曲のコールをまとめるサイト
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://konomi.platinumdis.co" # the base hostname & protocol for your site
fa_icon: fa-music

# homepage tiles
tiles_count: 16

# show cover images
show_covers: false

# social settings
twitter_url: https://twitter.com/konomin_call

# build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
  songs:
    output: true
    permalink: /:path/

sass:
  style: compressed

plugins:
  - jekyll-multiple-languages-plugin
  # - jekyll-pdf

include: [".nojekyll", "CNAME"]
exclude: ["README.md", "phantom_jekyll_theme.gemspec"]

languages: ["ja", "en"]
exclude_from_localizations: ["assets", ".nojekyll"]

# defaults:
#   -
#     scope:
#       path: ""
#       type: "songs"
#     values:
#       pdf: true