# site settings
title: 鈴木このみオンラインコールガイド
subtitle: 鈴木このみの楽曲のコールをまとめるサイト
baseurl: "/konomi-call" # the subpath of your site, e.g. /blog
url: "https://konomi.platinumdis.co" # the base hostname & protocol for your site
fa_icon: fa-music

# homepage tiles
tiles_count: 16

# show cover images
show_covers: false

# social settings
twitter_url: https://twitter.com/konomin_call

# build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
  songs:
    output: true
    permalink: /:path/

sass:
  style: compressed

plugins:
  - jekyll-multiple-languages-plugin

include: [".nojekyll", "CNAME"]
exclude: ["README.md", "phantom_jekyll_theme.gemspec"]

enable_i18n: true
default_locale_in_subfolder: false
languages: ["ja", "en"]
exclude_from_localizations: ["assets", ".nojekyll", "CNAME"]
