name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
  pdf:
    needs: deploy
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: southrop/html-to-pdf-action@main
        with:
          htmlFile: index.html,days-of-dash/index.html,watamote/index.html,this-game/index.html,absolute-soul/index.html,deep-red-heart/index.html,beat-your-heart/index.html,redo/index.html,love-is-my-rail/index.html,join-us/index.html,sky-blue-oasis/index.html,theater-of-life/index.html,akenai-yoru-ni/index.html,realize/index.html,a-beautiful-mistake/index.html,maiyuki/index.html,live-it-up/index.html
          outputFile: download.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - uses: southrop/html-to-pdf-action@main
        with:
          htmlFile: en/index.html,en/days-of-dash/index.html,en/watamote/index.html,en/this-game/index.html,en/absolute-soul/index.html,en/deep-red-heart/index.html,en/beat-your-heart/index.html,en/redo/index.html,en/love-is-my-rail/index.html,en/join-us/index.html,en/sky-blue-oasis/index.html,en/theater-of-life/index.html,en/akenai-yoru-ni/index.html,en/realize/index.html,en/a-beautiful-mistake/index.html,en/maiyuki/index.html,en/live-it-up/index.html
          outputFile: en/download.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add index.pdf
          git add en/index.pdf
          git commit -m 'Generated PDF'
          git push
